[package]
name = "mandate_memory"
edition = "2024"
license = "MIT"
authors = ["Nidhi (github.com/Nidhicodes)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
mandate_memory = "0x0"
